
server:
  port: 8081
spring:
#  项目名字
  application:
    name: test_rabbitmq_producer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    passowrd: guest
      #消息确认配置项
    listener:
     direct:
        acknowledge-mode: manual
     simple:
        acknowledge-mode: manual
      #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
      #确认消息已发送到队列(Queue)
    publisher-returns: true
